[build]
  command = "yarn build"
  publish = "build"

[build.environment]
  NODE_VERSION = "20.18.1"
  YARN_VERSION = "4.9.2"
  CI = "false"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
